// Copyright (c) 2017 ChromaWay Inc. See README for license information.

/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package net.postchain.ebft.messages;

import java.io.*;
import java.math.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class Status {

	@Component(0)
	public Long serial;

	@Component(1)
	public Long state;

	@Component(2)
	public Long round;

	@Component(3)
	public byte[] blockRID;	/* OPTIONAL */

	@Component(4)
	public Long height;

	@Component(5)
	public Boolean revolting;


	public boolean equals(Object obj) {
		if(!(obj instanceof Status)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static Status der_decode(InputStream in) throws IOException {
		return (Status)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65543);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(Status.class);
		AsnConverter serialConverter = LongConverter.INSTANCE;
		AsnConverter stateConverter = LongConverter.INSTANCE;
		AsnConverter roundConverter = LongConverter.INSTANCE;
		AsnConverter blockRIDConverter = OctetStringConverter.INSTANCE;
		AsnConverter heightConverter = LongConverter.INSTANCE;
		AsnConverter revoltingConverter = BooleanConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { serialConverter, stateConverter, roundConverter, blockRIDConverter, heightConverter, revoltingConverter });
	}


}
