//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.09 at 07:14:27 AM CET 
//


package net.postchain.base.gtxml;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for entryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}null"/>
 *         &lt;element ref="{}string"/>
 *         &lt;element ref="{}int"/>
 *         &lt;element ref="{}bytea"/>
 *         &lt;element ref="{}array"/>
 *         &lt;element ref="{}dict"/>
 *         &lt;element ref="{}param"/>
 *       &lt;/choice>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryType", propOrder = {
    "_null",
    "string",
    "_int",
    "bytea",
    "array",
    "dict",
    "param"
})
public class EntryType {

    @XmlElement(name = "null")
    protected Object _null;
    protected String string;
    @XmlElement(name = "int")
    protected BigInteger _int;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(HexBinaryAdapter.class)
    @XmlSchemaType(name = "hexBinary")
    protected byte[] bytea;
    protected ArrayType array;
    protected DictType dict;
    protected ParamType param;
    @XmlAttribute(name = "key")
    protected String key;

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setNull(Object value) {
        this._null = value;
    }

    /**
     * Gets the value of the string property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getString() {
        return string;
    }

    /**
     * Sets the value of the string property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setString(String value) {
        this.string = value;
    }

    /**
     * Gets the value of the int property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInt() {
        return _int;
    }

    /**
     * Sets the value of the int property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInt(BigInteger value) {
        this._int = value;
    }

    /**
     * Gets the value of the bytea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public byte[] getBytea() {
        return bytea;
    }

    /**
     * Sets the value of the bytea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBytea(byte[] value) {
        this.bytea = value;
    }

    /**
     * Gets the value of the array property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayType }
     *     
     */
    public ArrayType getArray() {
        return array;
    }

    /**
     * Sets the value of the array property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayType }
     *     
     */
    public void setArray(ArrayType value) {
        this.array = value;
    }

    /**
     * Gets the value of the dict property.
     * 
     * @return
     *     possible object is
     *     {@link DictType }
     *     
     */
    public DictType getDict() {
        return dict;
    }

    /**
     * Sets the value of the dict property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictType }
     *     
     */
    public void setDict(DictType value) {
        this.dict = value;
    }

    /**
     * Gets the value of the param property.
     * 
     * @return
     *     possible object is
     *     {@link ParamType }
     *     
     */
    public ParamType getParam() {
        return param;
    }

    /**
     * Sets the value of the param property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamType }
     *     
     */
    public void setParam(ParamType value) {
        this.param = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
