//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.21 at 03:39:32 PM EEST 
//


package net.postchain.base.gtxml;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for entryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="entryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}null"/>
 *         &lt;element ref="{}string"/>
 *         &lt;element ref="{}int"/>
 *         &lt;element ref="{}bytea"/>
 *         &lt;element ref="{}array"/>
 *         &lt;element ref="{}dict"/>
 *         &lt;element ref="{}param"/>
 *       &lt;/choice>
 *       &lt;attribute name="key" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "entryType", propOrder = {
    "value"
})
public class EntryType {

    @XmlElementRefs({
        @XmlElementRef(name = "array", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "param", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bytea", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "string", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "null", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "int", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dict", type = JAXBElement.class, required = false)
    })
    protected JAXBElement<?> value;
    @XmlAttribute(name = "key")
    protected String key;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ArrayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ParamType }{@code >}
     *     {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public JAXBElement<?> getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ArrayType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ParamType }{@code >}
     *     {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     {@link JAXBElement }{@code <}{@link Object }{@code >}
     *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     *     {@link JAXBElement }{@code <}{@link DictType }{@code >}
     *     
     */
    public void setValue(JAXBElement<?> value) {
        this.value = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
