//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.09 at 07:14:27 AM CET 
//


package net.postchain.base.gtxml;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for operationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="operationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}null" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}int" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}bytea" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}array" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}dict" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}param" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "operationType", propOrder = {
    "nullOrStringOrInt"
})
public class OperationType {

    @XmlElementRefs({
        @XmlElementRef(name = "bytea", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "param", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "null", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dict", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "int", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "string", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "array", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> nullOrStringOrInt;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the nullOrStringOrInt property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nullOrStringOrInt property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNullOrStringOrInt().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * {@link JAXBElement }{@code <}{@link ParamType }{@code >}
     * {@link JAXBElement }{@code <}{@link Object }{@code >}
     * {@link JAXBElement }{@code <}{@link DictType }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ArrayType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getNullOrStringOrInt() {
        if (nullOrStringOrInt == null) {
            nullOrStringOrInt = new ArrayList<JAXBElement<?>>();
        }
        return this.nullOrStringOrInt;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
