// Copyright (c) 2017 ChromaWay Inc. See README for license information.

/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package org.postchain.ebft.messages;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class BlockSignature {

	@Component(0)
	public byte[] blockRID;

	@Component(1)
	public Signature signature;


	public boolean equals(Object obj) {
		if(!(obj instanceof BlockSignature)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static BlockSignature der_decode(InputStream in) throws IOException {
		return (BlockSignature)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65547);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(BlockSignature.class);
		AsnConverter blockRIDConverter = OctetStringConverter.INSTANCE;
		AsnConverter signatureConverter = Signature.CONV;
		CONV.setComponentConverters(new AsnConverter[] { blockRIDConverter, signatureConverter });
	}


}
