// Copyright (c) 2017 ChromaWay Inc. See README for license information.

/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package org.postchain.ebft.messages;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class GetUnfinishedBlock {

	@Component(0)
	public byte[] blockRID;


	public boolean equals(Object obj) {
		if(!(obj instanceof GetUnfinishedBlock)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static GetUnfinishedBlock der_decode(InputStream in) throws IOException {
		return (GetUnfinishedBlock)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65538);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(GetUnfinishedBlock.class);
		AsnConverter blockRIDConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { blockRIDConverter });
	}


}
