// Copyright (c) 2017 ChromaWay Inc. See README for license information.

/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package org.postchain.ebft.messages;

import java.io.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class SignedMessage {

	@Component(0)
	public byte[] message;

	@Component(1)
	public byte[] pubkey;

	@Component(2)
	public byte[] signature;


	public boolean equals(Object obj) {
		if(!(obj instanceof SignedMessage)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static SignedMessage der_decode(InputStream in) throws IOException {
		return (SignedMessage)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65537);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(SignedMessage.class);
		AsnConverter messageConverter = OctetStringConverter.INSTANCE;
		AsnConverter pubkeyConverter = OctetStringConverter.INSTANCE;
		AsnConverter signatureConverter = OctetStringConverter.INSTANCE;
		CONV.setComponentConverters(new AsnConverter[] { messageConverter, pubkeyConverter, signatureConverter });
	}


}
