/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package com.chromaway.postchain.gtx.messages;

import java.io.*;
import java.util.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class GTXOperation {

	@Component(0)
	public String opName;

	@Component(1)
	public Vector<GTXValue> args;


	public boolean equals(Object obj) {
		if(!(obj instanceof GTXOperation)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static GTXOperation der_decode(InputStream in) throws IOException {
		return (GTXOperation)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65539);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(GTXOperation.class);
		AsnConverter opNameConverter = StringConverter.INSTANCE;
		AsnConverter argsConverter = new VectorConverter(GTXValue.CONV);
		CONV.setComponentConverters(new AsnConverter[] { opNameConverter, argsConverter });
	}


}
