/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package com.chromaway.postchain.gtx.messages;

import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.Component;
import org.asnlab.asndt.runtime.type.AsnType;

import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.util.Vector;

public class GTXTransaction {

    static {
        CONV = new AnnotationCompositeConverter(GTXTransaction.class);
        AsnConverter blockchainRIDConverter = OctetStringConverter.INSTANCE;
        AsnConverter operationsConverter = new VectorConverter(GTXOperation.CONV);
        AsnConverter signersConverter = new VectorConverter(OctetStringConverter.INSTANCE);
        AsnConverter signaturesConverter = new VectorConverter(OctetStringConverter.INSTANCE);
        CONV.setComponentConverters(new AsnConverter[]{blockchainRIDConverter, operationsConverter, signersConverter, signaturesConverter});
    }

	@Component(1)
	public Vector<GTXOperation> operations;

	@Component(2)
	public Vector<byte[]> signers;

	@Component(3)
	public Vector<byte[]> signatures;


	public boolean equals(Object obj) {
		if(!(obj instanceof GTXTransaction)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static GTXTransaction der_decode(InputStream in) throws IOException {
		return (GTXTransaction)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65540);

	public final static CompositeConverter CONV;

    @Component(0)
    public byte[] blockchainRID;


}
