/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package com.chromaway.postchain.gtx.messages;

import java.io.*;
import java.math.*;
import java.util.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class GTXValue {

	public static final int null_Chosen = 0;
	public static final int byteArrayChosen = 1;
	public static final int stringChosen = 2;
	public static final int integerChosen = 3;
	public static final int dictChosen = 4;
	public static final int arrayChosen = 5;

	public final int choiceID;

	@Alternative(0)
	public final Object null_;

	@Alternative(1)
	public final byte[] byteArray;

	@Alternative(2)
	public final String string;

	@Alternative(3)
	public final Long integer;

	@Alternative(4)
	public final Vector<DictPair> dict;

	@Alternative(5)
	public final Vector<GTXValue> array;


	private GTXValue(int choiceID, Object null_, byte[] byteArray, String string, Long integer, Vector<DictPair> dict, Vector<GTXValue> array) {
		this.choiceID = choiceID;
		this.null_ = null_;
		this.byteArray = byteArray;
		this.string = string;
		this.integer = integer;
		this.dict = dict;
		this.array = array;
	}

	public static GTXValue null_(Object null_) {
		return new GTXValue(null_Chosen, null_, null, null, null, null, null);
	}

	public static GTXValue byteArray(byte[] byteArray) {
		return new GTXValue(byteArrayChosen, null, byteArray, null, null, null, null);
	}

	public static GTXValue string(String string) {
		return new GTXValue(stringChosen, null, null, string, null, null, null);
	}

	public static GTXValue integer(Long integer) {
		return new GTXValue(integerChosen, null, null, null, integer, null, null);
	}

	public static GTXValue dict(Vector<DictPair> dict) {
		return new GTXValue(dictChosen, null, null, null, null, dict, null);
	}

	public static GTXValue array(Vector<GTXValue> array) {
		return new GTXValue(arrayChosen, null, null, null, null, null, array);
	}

	public boolean equals(Object obj) {
		if(!(obj instanceof GTXValue)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static GTXValue der_decode(InputStream in) throws IOException {
		return (GTXValue)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65538);

	public final static ChoiceConverter CONV;

	static {
		CONV = new AnnotationChoiceConverter(GTXValue.class);
		AsnConverter null_Converter = NullConverter.INSTANCE;
		AsnConverter byteArrayConverter = OctetStringConverter.INSTANCE;
		AsnConverter stringConverter = StringConverter.INSTANCE;
		AsnConverter integerConverter = LongConverter.INSTANCE;
		AsnConverter dictConverter = new VectorConverter(DictPair.CONV);
		AsnConverter arrayConverter = new VectorConverter(GTXValue.CONV);
		CONV.setAlternativeConverters(new AsnConverter[] { null_Converter, byteArrayConverter, stringConverter, integerConverter, dictConverter, arrayConverter });
	}


}
