/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package com.chromaway.postchain.ebft.messages;

import java.io.*;
import java.util.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class BlockData {

	@Component(0)
	public byte[] header;

	@Component(1)
	public byte[][] transactions;


	public boolean equals(Object obj) {
		if(!(obj instanceof BlockData)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static BlockData der_decode(InputStream in) throws IOException {
		return (BlockData)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65539);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(BlockData.class);
		AsnConverter headerConverter = OctetStringConverter.INSTANCE;
		AsnConverter transactionsConverter = new ArrayConverter(OctetStringConverter.INSTANCE);
		CONV.setComponentConverters(new AsnConverter[] { headerConverter, transactionsConverter });
	}


}
