/*
 * Generated by ASN.1 Java Compiler (http://www.asnlab.org/)
 * From ASN.1 module "Messages"
 */
package com.chromaway.postchain.base.messages;

import java.io.*;
import java.math.*;
import java.util.*;
import org.asnlab.asndt.runtime.conv.*;
import org.asnlab.asndt.runtime.conv.annotation.*;
import org.asnlab.asndt.runtime.type.AsnType;
import org.asnlab.asndt.runtime.value.*;

public class BlockHeader {

	@Component(0)
	public byte[] prevBlockHash;

	@Component(1)
	public byte[] rootHash;

	@Component(2)
	public Long timestamp;

	@Component(3)
	public Long height;

	@Component(4)
	public KeyValue[] extra;


	public boolean equals(Object obj) {
		if(!(obj instanceof BlockHeader)){
			return false;
		}
		return TYPE.equals(this, obj, CONV);
	}

	public void der_encode(OutputStream out) throws IOException {
		TYPE.encode(this, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV, out);
	}

	public static BlockHeader der_decode(InputStream in) throws IOException {
		return (BlockHeader)TYPE.decode(in, EncodingRules.DISTINGUISHED_ENCODING_RULES, CONV);
	}


	public final static AsnType TYPE = Messages.type(65538);

	public final static CompositeConverter CONV;

	static {
		CONV = new AnnotationCompositeConverter(BlockHeader.class);
		AsnConverter prevBlockHashConverter = OctetStringConverter.INSTANCE;
		AsnConverter rootHashConverter = OctetStringConverter.INSTANCE;
		AsnConverter timestampConverter = LongConverter.INSTANCE;
		AsnConverter heightConverter = LongConverter.INSTANCE;
		AsnConverter extraConverter = new ArrayConverter(KeyValue.CONV);
		CONV.setComponentConverters(new AsnConverter[] { prevBlockHashConverter, rootHashConverter, timestampConverter, heightConverter, extraConverter });
	}


}
